version: "3.3"
services:
  notify:
    build: .
    container_name: autochecker
    environment:
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
    ports:
      - 4000:4000
    restart: unless-stopped
